apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedido-service-at
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pedido-service-at
  template:
    metadata:
      labels:
        app: pedido-service-at
    spec:
      containers:
        - name: pedido-service-at
          image: rafaelloureioc/pedido-service-at:latest
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://my-sql:3306/AtDevOPS"
            - name: SPRING_DATASOURCE_USERNAME
              value: "sa"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "password"
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: pedido-service-at
spec:
  selector:
    app: pedido-service-at
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
